#**
#* Copyright 2023 TriOrb Inc.
#*
#* Licensed under the Apache License, Version 2.0 (the "License");
#* you may not use this file except in compliance with the License.
#* You may obtain a copy of the License at
#*
#*     http://www.apache.org/licenses/LICENSE-2.0
#*
#* Unless required by applicable law or agreed to in writing, software
#* distributed under the License is distributed on an "AS IS" BASIS,
#* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#* See the License for the specific language governing permissions and
#* limitations under the License.
#**

#==平面内の位置・姿勢==

# Translation along the X axis [m]. For relative movement, forward is positive.
float32 x
# Translation along the Y axis [m]. For relative movement, left is positive.
float32 y
# Heading angle [deg]. For relative movement, counter-clockwise is positive.
float32 deg
