#**
#* Copyright 2026 TriOrb Inc.
#*
#* Licensed under the Apache License, Version 2.0 (the "License");
#* you may not use this file except in compliance with the License.
#* You may obtain a copy of the License at
#*
#*     http://www.apache.org/licenses/LICENSE-2.0
#*
#* Unless required by applicable law or agreed to in writing, software
#* distributed under the License is distributed on an "AS IS" BASIS,
#* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#* See the License for the specific language governing permissions and
#* limitations under the License.
#**

#==[Service] Get MQTT broker (Fleet Management System endpoint)==
# GUI API: GET /system/config/mqtt/broker -> ROS 2 service /system/config/mqtt/broker/get
# Backend: triorb-system-cored SystemService.GetMqttBroker
# The GUI persists the FMS MQTT broker address here so it can be restored after a restart.
---
string host  # persisted MQTT broker host: IPv4 literal or hostname ("" = not configured)
uint16 port  # persisted MQTT broker TCP port (typical 1883 / 8883)
