#**
#* Copyright 2026 TriOrb Inc.
#*
#* Licensed under the Apache License, Version 2.0 (the "License");
#* you may not use this file except in compliance with the License.
#* You may obtain a copy of the License at
#*
#*     http://www.apache.org/licenses/LICENSE-2.0
#*
#* Unless required by applicable law or agreed to in writing, software
#* distributed under the License is distributed on an "AS IS" BASIS,
#* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#* See the License for the specific language governing permissions and
#* limitations under the License.
#**

#==[Service] Get system resource usage==
# GUI API: GET /system/resources -> ROS 2 service /system/resources/get
# Backend: triorb-system-cored SystemService.GetResources
---
std_msgs/Header header           # snapshot timestamp
float64 cpu_percent              # 0..100, all cores aggregated
float64 cpu_temperature_celsius  # 0 when unavailable
float64 gpu_percent              # 0 when unavailable
float64 gpu_temperature_celsius  # 0 when unavailable
float64 memory_percent           # 0..100
uint64 memory_total_bytes        # total physical memory
uint64 memory_used_bytes         # used physical memory
DiskUsage[] disks                # per mount point
bool success                     # false if the snapshot could not be taken
string message                   # error detail when success is false, empty otherwise
