#**
#* Copyright 2026 TriOrb Inc.
#*
#* Licensed under the Apache License, Version 2.0 (the "License");
#* you may not use this file except in compliance with the License.
#* You may obtain a copy of the License at
#*
#*     http://www.apache.org/licenses/LICENSE-2.0
#*
#* Unless required by applicable law or agreed to in writing, software
#* distributed under the License is distributed on an "AS IS" BASIS,
#* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#* See the License for the specific language governing permissions and
#* limitations under the License.
#**

#==[Service] ライセンスの有効化==
# GUI API: POST /system/license/activate -> ROS 2 service /system/license/set
# Backend: triorb-system-cored SystemService.ActivateLicense
string name                  # license (system) name
PackageVersion[] packages    # packages to license
---
bool success                 # false if activation failed
string message               # error detail when success is false, empty otherwise
