# Execute a saved route CSV file.

# ---- goal ----
string file_name
float32 ratio_speed
float32 bias_accuracy_xy
float32 bias_accuracy_deg
uint32 loop                    # Must be greater than zero.
---
# ---- result ----
bool success
string final_status            # Finished / RouteError / Stopped / Canceled
string message
---
# ---- feedback ----
TaskExecutionStatus status
